"""
Unit tests for the UUID v4 field validator on QueryRequest.thread_id
(Fix 1 — routes/query.py).

Contract under test
-------------------
QueryRequest.thread_id_must_be_uuid4() must:
1. Accept well-formed UUID v4 strings.
2. Reject any string that is not a UUID (arbitrary text, Redis key paths, etc.).
3. Reject UUID v1 / v3 / v5 strings (even though they are valid UUIDs, they are
   the wrong version and could be generated by clients under attacker control).
4. Reject malformed UUID-like strings (wrong length, wrong hyphens, wrong chars).
5. Raise pydantic ValidationError (not raw ValueError) so FastAPI converts it
   to HTTP 422 automatically.

Why this guard matters
----------------------
Without it a malicious client could pass "schema_hash" as thread_id, causing
run_agent() to write conversation history under "nl2sql:schema_hash" and
overwrite the schema drift baseline stored by schema_watcher.py.
"""

import pytest
from pydantic import ValidationError

from app.routes.query import QueryRequest


# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

def _make_request(thread_id: str, question: str = "Who scored the most runs?") -> QueryRequest:
    """Construct a QueryRequest; raises ValidationError on bad thread_id."""
    return QueryRequest(question=question, thread_id=thread_id)


# ---------------------------------------------------------------------------
# TestValidUUIDv4 — happy-path: valid v4 UUIDs are accepted
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestValidUUIDv4:

    @pytest.mark.parametrize("valid_uuid4", [
        "550e8400-e29b-41d4-a716-446655440000",
        "6ba7b810-9dad-41d1-80b4-00c04fd430c8",   # lower-hex v4 format (version nibble = 4)
        "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "aaaabbbb-cccc-4ddd-aeee-ffffffffffff",  # variant nibble 'a' = 10xx (valid)
        "00000000-0000-4000-8000-000000000000",    # minimal v4
        "ffffffff-ffff-4fff-bfff-ffffffffffff",    # max v4 (variant bits respected)
    ])
    def test_valid_uuid4_accepted(self, valid_uuid4: str):
        """Well-formed UUID v4 strings must pass validation without error."""
        req = _make_request(valid_uuid4)
        # Value is preserved (validator returns v unchanged)
        assert req.thread_id == valid_uuid4

    def test_valid_uuid4_preserves_exact_string(self):
        """The validator must return the original string, not a normalised version."""
        uid = "550e8400-e29b-41d4-a716-446655440000"
        req = _make_request(uid)
        assert req.thread_id == uid


# ---------------------------------------------------------------------------
# TestArbitraryStringRejected — arbitrary non-UUID strings are rejected
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestArbitraryStringRejected:

    @pytest.mark.parametrize("bad_thread_id", [
        "schema_hash",
        "nl2sql:cache:abc123",
        "nl2sql:chips:mythread",
        "../../../etc/passwd",
        "' OR 1=1 --",
        "admin",
        "hello world",
        "12345",
        "not-a-uuid-at-all",
        "00000000000000000000000000000000",    # 32 hex chars, no hyphens
        " ",                                   # whitespace only
    ])
    def test_arbitrary_string_rejected(self, bad_thread_id: str):
        """Non-UUID strings must raise ValidationError."""
        with pytest.raises(ValidationError) as exc_info:
            _make_request(bad_thread_id)
        # The error message must reference the thread_id field
        errors = exc_info.value.errors()
        assert any("thread_id" in str(e.get("loc", "")) for e in errors), (
            f"ValidationError did not mention thread_id. Errors: {errors}"
        )

    def test_redis_key_injection_blocked(self):
        """
        A Redis key that would overwrite the schema drift baseline must be
        rejected — this is the specific attack the guard prevents.
        """
        with pytest.raises(ValidationError):
            _make_request("schema_hash")

    def test_cache_key_prefix_blocked(self):
        """Redis cache keys must not be accepted as thread IDs."""
        with pytest.raises(ValidationError):
            _make_request("nl2sql:cache:deadbeef")

    def test_error_message_identifies_uuid4_requirement(self):
        """The ValidationError detail must include 'UUID v4' so clients understand the constraint."""
        with pytest.raises(ValidationError) as exc_info:
            _make_request("not-a-uuid")
        error_text = str(exc_info.value)
        assert "UUID v4" in error_text or "uuid" in error_text.lower(), (
            f"Expected UUID-related message, got: {error_text}"
        )


# ---------------------------------------------------------------------------
# TestWrongUUIDVersion — v1, v3, v5 UUIDs are valid UUIDs but wrong version
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestWrongUUIDVersion:

    @pytest.mark.parametrize("non_v4_uuid,version_label", [
        # UUID v1 — timestamp-based; version nibble is 1
        ("6ba7b810-9dad-11d1-80b4-00c04fd430c8", "v1"),
        # UUID v3 — MD5 name-based; version nibble is 3
        ("6ba7b810-9dad-31d1-80b4-00c04fd430c8", "v3"),
        # UUID v5 — SHA-1 name-based; version nibble is 5
        ("6ba7b810-9dad-51d1-80b4-00c04fd430c8", "v5"),
    ])
    def test_non_v4_uuid_rejected(self, non_v4_uuid: str, version_label: str):
        """UUID v1/v3/v5 strings must be rejected — only v4 is accepted."""
        with pytest.raises(ValidationError):
            _make_request(non_v4_uuid)

    @pytest.mark.parametrize("non_v4_uuid,version_label", [
        ("6ba7b810-9dad-11d1-80b4-00c04fd430c8", "v1"),
        ("6ba7b810-9dad-31d1-80b4-00c04fd430c8", "v3"),
        ("6ba7b810-9dad-51d1-80b4-00c04fd430c8", "v5"),
    ])
    def test_non_v4_raises_pydantic_validation_error_not_raw_value_error(
        self, non_v4_uuid: str, version_label: str
    ):
        """
        Confirm the exception is pydantic.ValidationError (not a raw ValueError)
        so FastAPI's 422 handler picks it up correctly.
        """
        try:
            _make_request(non_v4_uuid)
            pytest.fail(f"Expected ValidationError for {version_label} UUID {non_v4_uuid!r}")
        except ValidationError:
            pass  # correct — pydantic wraps the ValueError
        except ValueError as exc:
            pytest.fail(
                f"Got raw ValueError instead of pydantic ValidationError "
                f"for {version_label}: {exc}"
            )


# ---------------------------------------------------------------------------
# TestMalformedUUIDLikeStrings — strings that look like UUIDs but are broken
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestMalformedUUIDLikeStrings:

    @pytest.mark.parametrize("malformed", [
        # Wrong length
        "550e8400-e29b-41d4-a716-44665544000",     # one char short
        "550e8400-e29b-41d4-a716-4466554400000",   # one char long
        # Wrong hyphen placement
        "550e8400e29b41d4a716446655440000",         # no hyphens
        "550e8400-e29b41d4-a716-446655440000",      # missing one hyphen
        # Non-hex characters
        "550e8400-e29b-41d4-a716-44665544000z",
        "GGGGGGGG-GGGG-4GGG-GGGG-GGGGGGGGGGGG",
        # Empty string (already blocked by min_length=1 but test for safety)
        # Note: empty string raises a different validation error (min_length)
        # so we don't include it here — it still raises ValidationError
        # Version nibble is 0 (invalid)
        "550e8400-e29b-01d4-a716-446655440000",
    ])
    def test_malformed_uuid_rejected(self, malformed: str):
        """Malformed UUID-like strings must raise ValidationError."""
        with pytest.raises(ValidationError):
            _make_request(malformed)

    def test_uuid_with_braces_rejected(self):
        """{uuid} format (Windows-style) must be rejected."""
        with pytest.raises(ValidationError):
            _make_request("{550e8400-e29b-41d4-a716-446655440000}")

    def test_uuid_with_uppercase_rejected(self):
        """
        UUID.UUID normalises to lowercase; if the input is uppercase but valid
        v4, the canonical form won't round-trip (str(parsed) != v.lower() only
        if upper — but v.lower() == str(parsed) so uppercase IS accepted).
        Confirm behaviour: uppercase of a valid v4 should be accepted since
        v.lower() will equal str(parsed).
        """
        # This is a valid v4 in uppercase — the validator does v.lower() comparison
        uid_lower = "550e8400-e29b-41d4-a716-446655440000"
        uid_upper = uid_lower.upper()
        # The validator checks str(parsed) != v.lower(), so uppercase passes
        # (both sides are lowercase after .lower()).
        # This test documents and locks in that behaviour.
        req = _make_request(uid_upper)
        assert req.thread_id == uid_upper


# ---------------------------------------------------------------------------
# TestEdgeCases — boundary and integration edge cases
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestEdgeCases:

    def test_question_field_independent_of_thread_id_validation(self):
        """thread_id validation failure must not bleed into the question field."""
        with pytest.raises(ValidationError) as exc_info:
            _make_request("bad-thread-id", question="Who scored the most sixes?")
        errors = exc_info.value.errors()
        # Only thread_id should fail — not question
        failing_fields = [str(e.get("loc", "")) for e in errors]
        assert any("thread_id" in f for f in failing_fields)
        assert not any("question" in f for f in failing_fields)

    def test_valid_uuid4_with_valid_question_succeeds(self):
        """A complete valid request must pass all validators."""
        req = _make_request(
            "550e8400-e29b-41d4-a716-446655440000",
            question="How many sixes did Rohit Sharma hit?"
        )
        assert req.question == "How many sixes did Rohit Sharma hit?"
        assert req.thread_id == "550e8400-e29b-41d4-a716-446655440000"

    def test_validation_error_is_pydantic_type(self):
        """Must raise pydantic.ValidationError, not a raw ValueError."""
        with pytest.raises(ValidationError):
            _make_request("this is not a uuid")
        # Confirm it is NOT a raw ValueError being raised
        try:
            _make_request("this is not a uuid")
        except ValidationError:
            pass  # correct
        except ValueError as exc:
            pytest.fail(f"Got raw ValueError instead of pydantic ValidationError: {exc}")
