"use client";

import { useEffect, useRef, useState } from "react";

/**
 * ChartBlock — Phase 9: Visualization layer.
 *
 * Renders a Vega-Lite v5 chart spec using vega-embed.  Uses a dynamic import
 * to avoid SSR issues (vega-embed accesses the DOM at render time).
 *
 * The chart spec is generated by viz_agent.py on the backend when the user
 * asks for a chart, graph, or plot.
 *
 * TODO: Replace backend LLM spec generation with MCP chart server tool call
 *       for deterministic, schema-validated Vega-Lite output.
 *
 * TODO: Add a "Download as PNG" button using the vega-embed action menu
 *       (pass { actions: { export: true } } to embed()).
 */

interface ChartBlockProps {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  spec: Record<string, any>;
}

export default function ChartBlock({ spec }: ChartBlockProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    let vegaView: { finalize: () => void } | null = null;

    // Dynamic import prevents vega-embed from running on the server
    import("vega-embed").then(({ default: embed }) => {
      if (!containerRef.current) return;

      embed(containerRef.current, spec, {
        // Hide the Vega editor/export/source actions for a clean look
        actions: false,
        // Respect the container width
        width: "container",
        // TODO: Enable export action once download UX is designed
        // actions: { export: true, source: false, compiled: false, editor: false },
      })
        .then((result) => {
          vegaView = result.view;
        })
        .catch((err: Error) => {
          setError(`Chart render error: ${err.message}`);
        });
    });

    return () => {
      // Clean up the Vega view when the component unmounts
      vegaView?.finalize();
    };
    // Stringify spec to detect deep changes without unstable object identity
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(spec)]);

  if (error) {
    return (
      <p className="mt-3 text-xs text-red-400 italic">
        Could not render chart: {error}
      </p>
    );
  }

  return (
    <div
      ref={containerRef}
      className="mt-3 rounded-xl overflow-hidden bg-white"
      aria-label="Data visualization chart"
    />
  );
}
